name: flutter_analysis_server_plugin_sample
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0-290.4.beta

workspace:
  - packages/custom_plugin
  - packages/example
